### ISSUE TITLE
Firefox/Chrome extension

### ISSUE THREAD

**Issue by moeenio** [theforumhelpers/QuickReply#1]
Would love having a browser extension from this. A simple popup that shows this page.

**Comment by Accio1** [comment]
I don't really think that this is required.

**Comment by moeenio** [comment]
I know, I tried making one, but the copy function doesn't work

**Comment by Accio1** [comment]
Thanks for the suggestion though! Do you have any others? (For this or the main site)

**Comment by Accio1** [comment]
This has been resolved.
