### ISSUE TITLE
Custom quickreply

### ISSUE THREAD

**Issue by ghost** [theforumhelpers/QuickReply#10]
I am working on a project in which you can make custom notes and copy them by clicking a button, and i was wondering if you could implement my code in QuickReply so that you can also add Custom QuickReply Quotes.

**Comment by Accio1** [comment]
Hi there! This site is due for an overhaul, so I will be very active working on it when my Christmas break starts. I like the sound of this idea, but I'm wondering how it works. Does it save the custom replies each time, or do you have to re enter them each time you enter the site? I would hold off on submitting a pull request until the site has been overhauled, because submitting one now would probably just lead to it having to be updated. I'm assigning myself to this issue so that I don't forget about it.

**Comment by ghost** [comment]
Ok, so you can only save your custom quotes if this website supports server-side coding, which apparently Github doesn't support, so having the ability to save your own custom QuickReply quotes would take the entire server to move to a more advanced platform. So we'll have to stick with this for now:

> you have to re enter them each time you enter the site

I have the entire source code on glitch.com, so i guess you can copy-paste the code over here. Do you like it so far?

**Comment by Accio1** [comment]
Yes, unfortunately server side code isn't an option. There is a way to create a database using Google Sheets which works with only frontend, but I'm not sure that it is suitable for this site.

Also, please feel free to open more issues for anything that you think should be addressed in the site overhaul. (For QuickReply or the main site)

**Comment by ghost** [comment]
Well, i think i have a solution to this - i can embed the code onto a newer platform that supports server-side coding and we could possibly just use an `<iframe>` tag to embed it on QuickReply, so we might be able to save custom Quotes.

**Comment by Accio1** [comment]
I feel like using that opens us up to a higher chance of XSS and other vulnerabilities.

**Comment by ghost** [comment]
How? We have secure SSL connection and anti-XSS measures.

**Comment by Accio1** [comment]
I'd prefer to only use static/approved replies anyway. People could easily submit curse words or inappropriate links that would then be displayed on the site. This site is being linked on Scratch, which means that it must only have content that follows the community guidelines. This would increase the chance that NFE content could be displayed.

**Comment by ghost** [comment]
What? I think you got my idea all wrong, the customized quotes would only be shown to the user that wrote them. I made this suggestion since there are other quotes that i want to use, but they are not included in QuickReply itself.

**Comment by Accio1** [comment]
I'm still uncomfortable with the idea of including iFrames. I'm also focusing on making sure that this stays open source with as little dependencies as possible.

**Comment by ghost** [comment]
Ok, the iFrame idea is rejected. I will be thinking of what we could do tomorrow since it's 01:30 AM in my country right now. In this moment, my best idea is to use Save codes or something, but we'll discuss that tommorow.

**Comment by LankyBox01** [comment]
And also i am on my phone right now.

**Comment by Accio1** [comment]
The user who created this issue has since deleted their account. Therefore, I am closing this issue. I like this idea and it may be revisited in the future if we are able to find a way to implement server side code.
