### ISSUE TITLE
Update Responses

### ISSUE THREAD

**Issue by leahcimto** [theforumhelpers/QuickReply#12]
Some of these responses are outdated by forum standards, for example, some of these phrases a sometimes frowned upon, like making moderative posts. Some phrases that should be changed are the no advertising one and the list of suggestions one, as it is better to simply report the post.

**Comment by Accio1** [comment]
@leahcimto feel free to create a PR for this and then we can discuss after you have created it. It may also be a good idea to get some feedback after we have made our changes to see if any additional changes need to be made.

**Comment by leahcimto** [comment]
In progress, should be done soon.

**Comment by leahcimto** [comment]
Created at #13. Pending review.
