### ISSUE TITLE
Changes to QuickReply

### ISSUE THREAD

**Issue by gazalied** [theforumhelpers/QuickReply#14]
So, Instead of
>rejected for the following reason: [QUOTE FROM TOLORS].

What about
>rejected for the following reason: [quote=TOLORS]QUOTE FROM TOLORS[/quote].

**Comment by leahcimto** [comment]
Pull request up at #15

**Comment by Accio1** [comment]
@leahcimto the issue should be left open until the PR is merged.

**Comment by Accio1** [comment]
Closed by #15

**Comment by leahcimto** [comment]
> @leahcimto the issue should be left open until the PR is merged.

@Accio1 Oh shoot I had no idea I pressed close with comment >.< Sorry!

**Comment by Accio1** [comment]
> > @leahcimto the issue should be left open until the PR is merged.
> 
> @Accio1 Oh shoot I had no idea I pressed close with comment >.< Sorry!

@leahcimto It's all good :)
