### ISSUE TITLE
Bug: Favicon doesn't show up on the QuickReply Page.

### ISSUE THREAD

**Issue by LankyBox01** [theforumhelpers/QuickReply#19]
The favicon doesn't show up on the QuickReply Page, but it does on the other The Forum Helpers pages.
![1](https://user-images.githubusercontent.com/79767244/114233513-2035db80-9986-11eb-9c79-8f6f8e5dbfa9.PNG)

![2](https://user-images.githubusercontent.com/79767244/114233515-20ce7200-9986-11eb-980c-035198b32542.PNG)
![3](https://user-images.githubusercontent.com/79767244/114233516-21ff9f00-9986-11eb-9721-39dee42352ca.PNG)

**Comment by leahcimto** [comment]
I've just moved this to the quickreply repo.

**Comment by LankyBox01** [comment]
Wait you can move issues from one repo to another? That's cool XD
Anyways, may i be assigned? I'll fix it.

**Comment by leahcimto** [comment]
Yeah, lol. Since this is a small bug with an easy fix I hope it's ok if I assign you. Accio1, if you don't want me to do this kind of stuff (with assigning) please tell me.

**Comment by LankyBox01** [comment]
Yes, ok. i will fix it now

**Comment by LankyBox01** [comment]
It still doesn't show up for me...

**Comment by Accio1** [comment]
> It still doesn't show up for me...

It does for me so it is likely a caching issue.

**Comment by LankyBox01** [comment]
Agreed.
