### ISSUE TITLE
QuickReply nav block missing bottom margin

### ISSUE THREAD

**Issue by leahcimto** [theforumhelpers/QuickReply#22]
Title.

Screenshot:
<img width="183" alt="Screen Shot 2021-05-08 at 8 53 49 AM" src="https://user-images.githubusercontent.com/68165163/117539963-e97dd000-afda-11eb-9bd9-01cc9cc28b48.png">

This can be fixed in the css.

**Comment by gosoccerboy5** [comment]
<s>Bob the builder</s> I can fix this
can I go ahead and make a PR

**Comment by leahcimto** [comment]
Yes
