### ISSUE TITLE
Shouldn't this have the same header as the main site?

### ISSUE THREAD

**Issue by NilsTheBest** [theforumhelpers/QuickReply#3]
QuickReply is linked in the header of the main website, so logically shouldn't there be the header in that area too, so that we can go back to the main menu?

**Comment by Accio1** [comment]
Good idea, I'll get to that when I have the chance.

**Comment by Accio1** [comment]
Done! Do you think it should have a special footer unique to this page, or just the same one that the rest of the site has?

**Comment by Accio1** [comment]
Resolved
