### ISSUE TITLE
Broken button

### ISSUE THREAD

**Issue by gosoccerboy5** [theforumhelpers/QuickReply#31]
## What's wrong?
If you press a certain button in quickreply, it selects and copies the wrong text.
I will supply a video ([thanks to Github's new video sharing feature!!!!](https://github.blog/2021-05-13-video-uploads-available-github/)):

https://user-images.githubusercontent.com/82768218/118664773-5c473200-b7b7-11eb-9190-450eb4dcde77.mp4

Notice how the button has unexpected behavior.
## How to fix
Just replace the 7 with a 5 on line 61
https://github.com/theforumhelpers/QuickReply/blob/d43f2b53279404040e7de84234f08f2c7296415a/index.html#L59-L64
## Additional context:
[Thanks han614698 for reporting this bug!](https://scratch.mit.edu/users/leahcimto/#comments-141472590)

**Comment by JAYESH8011** [comment]
hey, can I fix this issue

**Comment by gosoccerboy5** [comment]
> hey, can I fix this issue

Feel free to fork this repository, and make a fix! If someone like @leahcimto sees your fix and thinks it's good, they will assign you, and then you can make a PR!

**Comment by leahcimto** [comment]
> hey, can I fix this issue

Yes, you can! In the future, if an issue is tagged with "good first issue" or "help wanted" just ask to be assigned! Remember to wait to be assigned before creating a PR.

**Comment by JAYESH8011** [comment]
Ok, can you assign me

**Comment by leahcimto** [comment]
Done!

**Comment by leahcimto** [comment]
@JAYESH8011 Are you still interested in working on this? :)

**Comment by leahcimto** [comment]
@JAYESH8011 Since you haven't replied or forked the repository I am going to assume you are no longer interested in doing this. I will make a patch for it :)
