### ISSUE TITLE
Bug: Stylesheet does not work.

### ISSUE THREAD

**Issue by Steve0Greatness** [theforumhelpers/QuickReply#36]
When going to quick reply(in any theme) it always shows:
![Screenshot 2021-06-12 2 23 35 PM](https://user-images.githubusercontent.com/75220768/121789315-d4700000-cb89-11eb-9fb1-c5b2e8dfab0a.png)
This isn't something that should happen, considering it's the use of the site(other than things that can be seen elsewhere)

**Comment by BarelySmooth** [comment]
I just noticed it. I think the ```stylesheet.css``` file should be updated here too.

**Comment by Steve0Greatness** [comment]
I know the issue. Instead of making the html element have the class for light and dark mode, it's that the body has it.

**Comment by Steve0Greatness** [comment]
@Accio1, can I be assigned?

**Comment by Accio1** [comment]
@Steve0Greatness good catch! Feel free to submit a fix.

**Comment by Steve0Greatness** [comment]
> @Steve0Greatness good catch! Feel free to submit a fix.

I've started work on it, it's more than just the css that isn't working. You can't switch themes.
I've fixed this, but something weird is happening, I think it would be easier if the 2 stylesheets were 1.

_edit: [link to viewing](https://quickreply.stevesgreatness.repl.co/), [link to replit](https://replit.com/@StevesGreatness/QuickReply)_

**Comment by Accio1** [comment]
At this point, switching themes is not required for quickreply. It should only be light mode, which can be done by adding class="lightMode" to the html tag. Switching themes will come later.

**Comment by Steve0Greatness** [comment]
> At this point, switching themes is not required for quickreply. It should only be light mode, which can be done by adding class="lightMode" to the html tag. Switching themes will come later.

ok then

**Comment by Steve0Greatness** [comment]
@Accio1 done! Everything should now work(from local testing), I'll get the pr up in a few
