### ISSUE TITLE
License file needed

### ISSUE THREAD

**Issue by ghost** [theforumhelpers/QuickReply#4]
This is currently proprietary software with shared source code. It could do with a license file (preferably a MIT license)

**Comment by leahcimto** [comment]
@Accio1 could you please do this soon

**Comment by Accio1** [comment]
@leahcimto whoops! I forgot, I will add this now.

**Comment by leahcimto** [comment]
Thanks!

**Comment by Accio1** [comment]
I just committed it straight to master.
